### ISSUE TITLE
Crash on re-launch after first run on Mac OS

### ISSUE THREAD

**Issue by ktorn** [ssbc/patchwork-electron#13]
I'm running into a reproducible bug with patchwork 2.7 on Mac OS X 10.11 (installed from `ssb-patchwork-electron_2.7.0.dmg`).

It runs well the first time I launch it, but if I close it and try to open it again, it crashes, and keeps crashing every time I try to re-launch it.

I checked that it isn't still running. Both `Patchwork` and the two `Patchwork Helper` processes disappear, and also it stops listening on any ports (on my machine it listens on `7777` and `8008` whilst running).

Only a reboot of the Mac allows me to open Patchwork again, and I need to keep it open because closing it means I can't open until yet another Mac reboot.

The only related log I could find (under Console) is:
`com.apple.xpc.launchd[1]: (com.ssbc.patchwork.374112[27736]) Service exited with abnormal code: 1`

**Comment by pfrazee** [comment]
I wonder if this could be an electron bug.

**Comment by emilbayes** [comment]
I'm having the same issue. Here's the output if I start `Patchwork` from terminal:

```
MacOS $ ./Patchwork 
[CFG] Password: NO.
[CFG] TLS: NO.
[CFG] Remote Access: NO.
Patchwork - Copyright (C) 2015-2016 Secure Scuttlebutt Consortium
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under certain conditions (GPL-3.0).

Starting...
Loading plugins from /Users/emil/.ssb/node_modules
Log level: notice
Serving at http://localhost:7777

Error: port 8008 isn't available. Is Patchwork already running?
```

However a `lsof` both port `7777` and `8008` reveal that no process is listening on either of those ports.

**Comment by clehner** [comment]
Does `netstat -ltnp | grep 8008` show anything?
how about `ps aux|grep Patchwork`
or `ps aux|grep electron`?

Does the issue still happen after waiting a few minutes? After logging out and logging back in? After rebooting?

**Comment by ktorn** [comment]
After upgrading to version 2.10.0 (Mac OS dmg install) I can no longer reproduce the issue. It works ok for me now.

**Comment by ktorn** [comment]
Even though I no longer experience the issue I'd like to know where to find Patchwork's log files (running the Mac OS dmg install).

Whilst running, on ActivityMonitor I looked through Patchwork's list of open files and could not find anything resembling a main log file.

**Comment by clehner** [comment]
@ktorn Patchwork doesn't write a log file, only to stdout. To see the output, try runing the executable from the command line. e.g. `/Applications/Patchwork.app/Contents/MacOS/Patchwork`

**Comment by ktorn** [comment]
This problem re-appeared for me. Starting from cli gives the exact same error as reported by @emilbayes above.

`netstat` doesn't really work the same way in MacOS as it does in Linux, but running `lsof -i -n -P | grep TCP | grep 8008` yielded no results.

For the time being I'm running it from source, having modified every instance of '8008' with '8009' (mostly within dependency modules confs) .

As a sanity test, running the same `lsof -i -n -P | grep TCP | grep 8009` whilst running the modified instance produces the expected result:
`node      57224            user   18u  IPv6 0x1f82d3b80db1bd42      0t0    TCP *:8009 (LISTEN)`

**Comment by mmckegg** [comment]
@ktorn the port that gets left open is **not** a TCP port, it is a **UDP port**. That might help you track it down. 

I've heard that @emilbayes has been experiencing this problem recently and has been trying to figure out what causes it. No clear ideas yet. I am running macOS 10.11.6 and have never experienced it. 

If you disable local peer discovery, the issue is avoided: https://github.com/ssbc/patchwork/blob/master/server-process.js#L37

``` js
  var createSbot = require('scuttlebot')
    .use(require('scuttlebot/plugins/master'))
    .use(require('./lib/persistent-gossip'))
    .use(require('./lib/friends-with-gossip-priority'))
    .use(require('scuttlebot/plugins/replicate'))
    .use(require('ssb-blobs'))
    .use(require('scuttlebot/plugins/invite'))
    .use(require('scuttlebot/plugins/block'))
    .use(require('scuttlebot/plugins/logging'))
    .use(require('scuttlebot/plugins/private'))
   // .use(require('scuttlebot/plugins/local')) comment out this line
    .use(require('ssb-notifier'))
    .use(require('./api'))
```

**Comment by ktorn** [comment]
@mmckegg:

> the port that gets left open is not a TCP port, it is a UDP port. 

Ah, that was important. Thanks for the clarification.
So, this is really odd, I can see the port open, but the associated PID (and all it's children) just aren't there any more.

Since this is no longer really specific to Patchwork but seems like a more general OS X issue, hopefully someone else will have run into this. I've added a [question in StackExchange](http://stackoverflow.com/questions/40512274/release-udp-port-used-by-dead-process-on-os-x).

However, for your reference, I did eventually find the pid responsible with:

`netstat -tulnvp udp | grep 8008`

More details in the SE question.

**Comment by clehner** [comment]
There is an answer on that SO question saying to use set SO_REUSEADDR on the socket. The equivalent with node should be to use {reuseAddr: true} when creating the socket with dgram.createSocket (see https://nodejs.org/api/dgram.html ). However, Emil reported this doesn't work when I suggested it a few days ago; YMMV.

**Comment by wojo** [comment]
Found your SO article @ktorn and having the same issue with a different application, but same exact symptoms. Subscribing here and will update this thread if I find a solution as well.

**Comment by glukki** [comment]
Not sure: is there the same issue in docker?
https://forums.docker.com/t/port-mappings-are-not-released/10565
