### ISSUE TITLE
Auto-update application on Windows

### ISSUE THREAD

**Issue by clehner** [ssbc/patchwork-electron#8]
One way to do this would be to use [`electron-installer-windows`](https://github.com/uunindented/electron-installer-windows) in the release script.

`electron-installer-windows` uses Squirrel.Windows which supports [distributing updates in GitHub releases](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/github.md)

A [code signing certificate](https://msdn.microsoft.com/en-us/library/windows/hardware/hh801887.aspx) is required

**Comment by pfrazee** [comment]
Intriguing, let's look into this
